language: rust

rust:
  - nightly

cache:
  cargo: true

addons:
  apt:
    sources:
      - elasticsearch-2.x
    packages:
      - elasticsearch

services:
  - elasticsearch

script:
  - cargo test && cargo build --release

deploy:
  # merge in master => deploy it to staging
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: XteD60xV4InzoAfQkeFBiVaRhLYl/wH5PbZ7OASCPIZ9x1CKLg3BlcYoxMVdBvt1mc3eZ2VuNnaECmTjDmt82NIA0tX902S1ELgD3W6mn+aUDYG21BK0dkh+llJLM9udUC0L5CcZikdTOGgRnY0EHYlJgK6DS5CEfQEngQKIfuPOoiDhKLcfxjZ1+rHrjwsBDbVQkXn7XG2+ZUMYs9DTvhYH5ynJgfYQnv+zuuBieXmxLDcnwxcsrUHW7HDQbzFPucmlB10NWkipUiM+I8KuwvBQ8RuqWpCIigx0E44VoRqh3uj0z7FgHElcaAKV9s94rgk2Oc45wyzYVIJ22rFbaYh2i8lbuCH3akErkhGOtLGaRJsh/BaT82Q7goUP1pxHWXmLkFz2B65luYqLr8CVQW7CKA77R3NJqn3WPRfGaJi5geqNMngGm2gT7yx857vsp8F22dpFO0kGZM3JiKkt76Cyipj9RM1q0pe/Une+ub5Azqt5QGgA9/ZXp1uJ8bhW/65cfY1XNsQRxZcr1C5L1Ig3xD+xRKTRg0fVCVG9BsnX2Ypd6XIxxkentCgY7LGv6WMiMDWUSEcQg7fuTxiJzUxUunT8doJQ8ZSoaQnqogp0NucwgACsRF3fVTasA3beVAAjRIrJ2aZs9lb30zf4+SVzlj1oSdN81VNib2zEb4k=
    app: staging-searchspot
    on:
      repo: honeypotio/searchspot
      branch: master
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: XteD60xV4InzoAfQkeFBiVaRhLYl/wH5PbZ7OASCPIZ9x1CKLg3BlcYoxMVdBvt1mc3eZ2VuNnaECmTjDmt82NIA0tX902S1ELgD3W6mn+aUDYG21BK0dkh+llJLM9udUC0L5CcZikdTOGgRnY0EHYlJgK6DS5CEfQEngQKIfuPOoiDhKLcfxjZ1+rHrjwsBDbVQkXn7XG2+ZUMYs9DTvhYH5ynJgfYQnv+zuuBieXmxLDcnwxcsrUHW7HDQbzFPucmlB10NWkipUiM+I8KuwvBQ8RuqWpCIigx0E44VoRqh3uj0z7FgHElcaAKV9s94rgk2Oc45wyzYVIJ22rFbaYh2i8lbuCH3akErkhGOtLGaRJsh/BaT82Q7goUP1pxHWXmLkFz2B65luYqLr8CVQW7CKA77R3NJqn3WPRfGaJi5geqNMngGm2gT7yx857vsp8F22dpFO0kGZM3JiKkt76Cyipj9RM1q0pe/Une+ub5Azqt5QGgA9/ZXp1uJ8bhW/65cfY1XNsQRxZcr1C5L1Ig3xD+xRKTRg0fVCVG9BsnX2Ypd6XIxxkentCgY7LGv6WMiMDWUSEcQg7fuTxiJzUxUunT8doJQ8ZSoaQnqogp0NucwgACsRF3fVTasA3beVAAjRIrJ2aZs9lb30zf4+SVzlj1oSdN81VNib2zEb4k=
    app: release-staging-searchspot
    on:
      repo: honeypotio/searchspot
      branch: master
  # new tag => deploy master to release-staging and production
  - provider: heroku
    skip_cleanup: true
    api_key:
      secure: XteD60xV4InzoAfQkeFBiVaRhLYl/wH5PbZ7OASCPIZ9x1CKLg3BlcYoxMVdBvt1mc3eZ2VuNnaECmTjDmt82NIA0tX902S1ELgD3W6mn+aUDYG21BK0dkh+llJLM9udUC0L5CcZikdTOGgRnY0EHYlJgK6DS5CEfQEngQKIfuPOoiDhKLcfxjZ1+rHrjwsBDbVQkXn7XG2+ZUMYs9DTvhYH5ynJgfYQnv+zuuBieXmxLDcnwxcsrUHW7HDQbzFPucmlB10NWkipUiM+I8KuwvBQ8RuqWpCIigx0E44VoRqh3uj0z7FgHElcaAKV9s94rgk2Oc45wyzYVIJ22rFbaYh2i8lbuCH3akErkhGOtLGaRJsh/BaT82Q7goUP1pxHWXmLkFz2B65luYqLr8CVQW7CKA77R3NJqn3WPRfGaJi5geqNMngGm2gT7yx857vsp8F22dpFO0kGZM3JiKkt76Cyipj9RM1q0pe/Une+ub5Azqt5QGgA9/ZXp1uJ8bhW/65cfY1XNsQRxZcr1C5L1Ig3xD+xRKTRg0fVCVG9BsnX2Ypd6XIxxkentCgY7LGv6WMiMDWUSEcQg7fuTxiJzUxUunT8doJQ8ZSoaQnqogp0NucwgACsRF3fVTasA3beVAAjRIrJ2aZs9lb30zf4+SVzlj1oSdN81VNib2zEb4k=
    app: production-searchspot
    on:
      repo: honeypotio/searchspot
      branch: master
      tags: true
