[package]
name    = "searchspot"
version = "0.15.1"

repository  = "https://github.com/honeypotio/searchspot"
authors     = ["Giovanni Capuano <webmaster@giovannicapuano.net>"]
license     = "BSD-2-Clause"
description = "The service responsible for Honeypot's ElasticSearch data"
keywords    = ["elasticsearch"]

[dependencies]
chrono       = "0.4"

iron         = "0.5"
router       = "0.5"
logger       = "0.3"
params       = "0.6"
persistent   = "0.3"
unicase      = "1.0"

lazy_static  = "0.2"
maplit       = "0.1"
oath         = "0.10"
log          = "0.3"
rollbar      = "0.4"
backtrace    = "0.2"
toml         = "0.4"

serde        = "1.0"
serde_json   = "1.0"
serde_derive = "1.0"

rs-es = "0.10"

[lib]
name = "searchspot"
path = "src/lib.rs"

[[bin]]
name = "searchspot"
path = "src/main.rs"
doc  = false
