[es]
url   = "http://localhost:9200"
index = "sample_index"
# tests contained in resources/* will use the index field
# as prefix for their own index to avoid race conditions

[http]
host = "127.0.0.1"
port = 3001

[auth]
enabled = true
read    = "icsbqwdg7ukqluav"
write   = "7x2ockhyff4fmm5n"
